### ISSUE TITLE
Integer/Float datatype error

### ISSUE THREAD

**Issue by AIdeveloper-oz** [YuvalNirkin/python_face_swap#1]
I installed all the requirements, the input image datatype is also uint8. Cant find where it gets changed. Help if you could. Thanks 
`(seg-swap) F:\swapping\python_face_swap>python face_swap_image.py -s tama.jpg -t milroy.jpg -b
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
uint8
Traceback (most recent call last):
  File "face_swap_image.py", line 35, in <module>
    rendered_img = fs.swap(target_img, target_seg)
  File "F:\swapping\python_face_swap\faceswap.py", line 50, in swap
    output = cv2.seamlessClone(rendered_img, target_img, mask, center, cv2.NORMAL_CLONE)
TypeError: integer argument expected, got float`

**Comment by YuvalNirkin** [comment]
What is your OpenCV version?

**Comment by AIdeveloper-oz** [comment]
Name: opencv-python
Version: 4.3.0.36
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: None
Author-email: None
License: MIT
Location: c:\users\maya-naveenkumar\anaconda3\envs\seg-swap\lib\site-packages
Requires: numpy

**Comment by YuvalNirkin** [comment]
They made some non backward compatible changes for seamlessClone in the new versions of OpenCV. You'll have to use the an older version, probably v3.x.

**Comment by AIdeveloper-oz** [comment]
I got the issue cleared, but the output is not good. In every instance, the swapped mask looks clear when its saved individually, but after seamlessclone, the target image is so brighter and the src image is not seen.  Have I gone wrong anywhere?
![swapout](https://user-images.githubusercontent.com/59594140/87040815-e6755000-c20e-11ea-910c-dd5545c48a12.PNG)

**Comment by AIdeveloper-oz** [comment]
Hi YuvalNirkin, I got rid of this lighting issue.
